import type { Metadata } from "next";
import { Noto_Sans_Thai, Mitr } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/footer";
import NavBar from "@/app/components/navbar";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai"],
  display: "swap",
});

const mitr = Mitr({
  variable: "--font-mitr",
  subsets: ["thai"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansThai.variable} ${mitr.variable}`}>
        <div className="flex min-h-screen flex-col">
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
